name: Ramanujan Raghavan
url: .
lsi: false
safe: true
source: .
plugins:
        - jekyll-figure
incremental: false
highlighter: rouge
gist:
        noscript: false
kramdown:
        parse_block_html: true
        math_engine: mathjax
        syntax_highlighter: rouge

