name: Ramanujan Raghavan
url: .
lsi: false
safe: true
source: .
plugins:
        - jekyll-figure
exclude:
        - CLAUDE.md
        - README.md
incremental: false
highlighter: rouge
gist:
        noscript: false
kramdown:
        parse_block_html: true
        math_engine: mathjax
        syntax_highlighter: rouge
defaults:
        - scope:
                  path: ""
                  type: posts
          values:
                  layout: post
                  permalink: /blog/:title/

